<a href="https://colab.research.google.com/github/ShreyasKadiri/Machine_Learning/blob/main/Word_Embedding_Techniques_using_Embedding_Layer_in_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Word Embedding Techniques using Embedding Layer in Keras

In [4]:
#Importing the libraries
from tensorflow.keras.preprocessing.text import one_hot


In [5]:
### sentences
sentences = [  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
### Vocabulary size
vocabulary_size=10000

In [7]:
#One Hot Representation

In [9]:
onehot_representation = [one_hot(words,vocabulary_size)for words in sentences] 
print(onehot_representation)

[[293, 9637, 7665, 9224], [293, 9637, 7665, 6389], [293, 9216, 7665, 2022], [8970, 7518, 5686, 5841, 8081], [8970, 7518, 5686, 5841, 5818], [3417, 293, 5878, 7665, 2772], [9513, 3703, 5780, 5841]]


In [11]:
#Word Embedding Representation

import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
sentence_length=8
embedded_sentences=pad_sequences(onehot_representation,padding='pre',maxlen=sentence_length)
print(embedded_sentences)

[[   0    0    0    0  293 9637 7665 9224]
 [   0    0    0    0  293 9637 7665 6389]
 [   0    0    0    0  293 9216 7665 2022]
 [   0    0    0 8970 7518 5686 5841 8081]
 [   0    0    0 8970 7518 5686 5841 5818]
 [   0    0    0 3417  293 5878 7665 2772]
 [   0    0    0    0 9513 3703 5780 5841]]


In [13]:
dimensions = 10
model=Sequential()
model.add(Embedding(vocabulary_size,10,input_length=sentence_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
print(model.predict(embedded_sentences))

[[[ 0.04618141 -0.03055326 -0.01859075  0.01014369  0.0324523
    0.00910908 -0.01412375 -0.0296694   0.00570649  0.0180322 ]
  [ 0.04618141 -0.03055326 -0.01859075  0.01014369  0.0324523
    0.00910908 -0.01412375 -0.0296694   0.00570649  0.0180322 ]
  [ 0.04618141 -0.03055326 -0.01859075  0.01014369  0.0324523
    0.00910908 -0.01412375 -0.0296694   0.00570649  0.0180322 ]
  [ 0.04618141 -0.03055326 -0.01859075  0.01014369  0.0324523
    0.00910908 -0.01412375 -0.0296694   0.00570649  0.0180322 ]
  [-0.02555875  0.0163896  -0.03867697 -0.00588111 -0.00839573
   -0.04648185 -0.01349407 -0.04797512 -0.00732094 -0.02774209]
  [-0.04315779 -0.03927777 -0.03982043  0.02043952 -0.04076991
    0.00867292 -0.04158714  0.00488671  0.02840853 -0.04611252]
  [-0.03587891 -0.04071647  0.00468225  0.0100626  -0.00042142
   -0.04100668 -0.04092801 -0.00119486  0.0431054   0.04063454]
  [-0.03459489  0.00257429  0.01304487 -0.00457395 -0.04287753
    0.01489886  0.01830628  0.04557676  0.01410921 -

In [17]:
embedded_sentences[0]

array([   0,    0,    0,    0,  293, 9637, 7665, 9224], dtype=int32)

In [18]:
print(model.predict(embedded_sentences)[0])

[[ 0.04618141 -0.03055326 -0.01859075  0.01014369  0.0324523   0.00910908
  -0.01412375 -0.0296694   0.00570649  0.0180322 ]
 [ 0.04618141 -0.03055326 -0.01859075  0.01014369  0.0324523   0.00910908
  -0.01412375 -0.0296694   0.00570649  0.0180322 ]
 [ 0.04618141 -0.03055326 -0.01859075  0.01014369  0.0324523   0.00910908
  -0.01412375 -0.0296694   0.00570649  0.0180322 ]
 [ 0.04618141 -0.03055326 -0.01859075  0.01014369  0.0324523   0.00910908
  -0.01412375 -0.0296694   0.00570649  0.0180322 ]
 [-0.02555875  0.0163896  -0.03867697 -0.00588111 -0.00839573 -0.04648185
  -0.01349407 -0.04797512 -0.00732094 -0.02774209]
 [-0.04315779 -0.03927777 -0.03982043  0.02043952 -0.04076991  0.00867292
  -0.04158714  0.00488671  0.02840853 -0.04611252]
 [-0.03587891 -0.04071647  0.00468225  0.0100626  -0.00042142 -0.04100668
  -0.04092801 -0.00119486  0.0431054   0.04063454]
 [-0.03459489  0.00257429  0.01304487 -0.00457395 -0.04287753  0.01489886
   0.01830628  0.04557676  0.01410921 -0.0190833 ]]